Data:
  data_path: "/home/yxfeng/project2/sci2/data/数据100mm流体域.xlsx"  # 输入数据路径（Excel）
  sheet_name: "数据100mm流体域"
  format: "auto"                 # auto|excel|csv （强制解析格式）
  sheet: 0   
  index_start: 8                  # Excel工作表索引或名称（仅excel）
  features: ["% x", "y", "z"]         # 特征列
  targets: ["T (K)", "spf.U (m/s)", "u (m/s)", "p (Pa)"]        # 目标
  output_dir: "/home/yxfeng/project2/sci925/outputs"      # 结果输出目录（绝对路径）
  log_dir: "/home/yxfeng/project2/sci925/logs"      # 日志输出目录（绝对路径）
  test_ratio: 0.2               # 验证/测试占比
  random_state: 42
  scaler_name: "standardscaler"
  batch_size: 64


Train:
  epochs: 1000
  is_eval: True
  optimizer: 'adam'
  loss_function: 'mse'
  scheduler: 'cosine'
  optimizer_config: {}
  loss_function_config: {}
  scheduler_config: {}
  save_dir: '/home/yxfeng/project2/sci925/outputs'
  load_model_path: '/home/yxfeng/project2/sci925/outputs/model/model.pth'
  log_interval: 10
  log_dir: 'logs'
  log_freq: 10
  is_log: True
  device: 'cuda'
  save_freq: 100
  is_save: True
  early_stopping: True
  patience: 50
  min_delta: 1e-4
  save_best_only: True
  is_pinn: True
  physics_weight: 1.0
  original_loss_weight: 1.0

Optimizer:
  name: 'adam'
  name_list :
    - 'adam'
    - 'sgd'
    - 'adamw'
  lr_range: (1e-3,1e-4)
  weight_decay_range: (1e-5,1e-6)
  lr: 1e-3
  weight_decay: 1e-5
  betas: (0.9,0.999)
  momentum: 0.9
  eps: 1e-8


Scheduler:
  name: 'cosine'
  lr_min: 1e-6
  lr_max: 1e-3
  T_max: 100
  eta_min: 1e-6
  last_epoch: -1
  verbose: False


LossFunction:
  name: 'mse'


logger:
  name: 'logger'
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    - name: 'file_handler'
      level: 'INFO'
      formatter: 'simple'
      filename: 'logs/logger.log'


Model:
  name_list: 
    - 'mlp'
    - 'lstm'
    - 'grmlp'
    - 'agtmlp'
    - 'resmlp'
    - 'gru'
    - 'cnn1d'
    - 'transformer'
    - 'wide_deep'

  input_dim: 3
  dropout: 0.2
  output_dim1: 4
  output_dim2: 1

  model_name:
   'mlp'

  mlp:
    hidden_dim: 128
    num_blocks: 8
    dropout: 0.2
    
  lstm:
    hidden_dim: 128
    num_blocks: 8
    dropout: 0.2
  
  grmlp:
    hidden_dim: 128
    depth: 8
    dropout: 0.2
  
  agtmlp:
    hidden_dim: 128
    depth: 8
    dropout: 0.2

  resmlp:
    hidden_dim: 128
    depth: 8
    dropout: 0.2

  gru:
    hidden_dim: 128
    num_layers: 4
    dropout: 0.1

  cnn1d:
    channels: 64
    depth: 4
    kernel_size: 3
    dropout: 0.1

  transformer:
    hidden_dim: 128
    depth: 4
    num_heads: 8
    dropout: 0.1

  wide_deep:
    deep_hidden: 128
    deep_layers: 3
    dropout: 0.1

swanlab:
  use_swanlab: True
  experiment_name: "physics_informed_nn_experiment_001"
  project_name: "sci2"
  description: "Physics-informed neural network for fluid dynamics simulation"
